const COMPANY_INFO = { companyName: "MNSOFT", companyLegalName: "MNSOLUÇÕES TECNOLÓGICAS & CONSULTORIA LTDA", companyCnpj: "18.160.057/0001-13", commercialEmail: "comercial@mnsoft.com.br", telegramBot: "@hablitflowmns_bot" };
const SENSITIVE_REPLY = "Não posso ajudar com informações sensíveis ou ações que comprometam a segurança. Posso ajudar com dúvidas sobre o uso do HabitFlow ou encaminhar você para o suporte da MNSOFT.";
const PROMPT_INJECTION_REPLY = "Não posso seguir instruções que tentem alterar minhas regras de segurança ou acessar informações internas. Posso ajudar com o uso do HabitFlow ou encaminhar você ao suporte.";
const UNKNOWN_REPLY = "Não tenho essa informação com segurança. Posso encaminhar você para o suporte da MNSOFT.";
const INTENTS = [
 { intent:"greeting", keywords:["oi","olá","ola","bom dia","boa tarde","boa noite"], answer:"Olá! Sou o Assistente HabitFlow. Posso ajudar com hábitos, streaks, progresso, planos, privacidade e suporte." },
 { intent:"product_overview", keywords:["o que é","habitflow","produto","serve","benefícios","beneficios"], answer:"O HabitFlow é um micro SaaS simples para acompanhar hábitos, manter consistência diária, visualizar streaks e progresso dos últimos 30 dias." },
 { intent:"create_habit_help", keywords:["criar hábito","novo hábito","cadastrar hábito","adicionar hábito"], answer:"Para criar um hábito, acesse a aba Hoje, clique em Novo hábito, informe nome, categoria e cor, e salve. No plano gratuito, você pode manter até 5 hábitos ativos." },
 { intent:"edit_habit_help", keywords:["editar hábito","alterar hábito","mudar hábito"], answer:"Para editar, use o ícone de lápis no card do hábito, ajuste nome, categoria ou cor e salve." },
 { intent:"archive_habit_help", keywords:["arquivar","excluir hábito","apagar hábito"], answer:"O HabitFlow usa arquivamento lógico: o hábito sai da lista principal, mas o histórico é preservado e pode ser restaurado no Perfil." },
 { intent:"restore_habit_help", keywords:["restaurar","recuperar hábito","hábitos arquivados"], answer:"Para restaurar um hábito, abra Perfil, acesse Hábitos arquivados e clique em Restaurar." },
 { intent:"complete_habit_help", keywords:["marcar como feito","concluir","desmarcar","feito hoje"], answer:"Na aba Hoje, clique em Marcar como feito. Se precisar desfazer, clique novamente no botão do hábito concluído." },
 { intent:"streak_help", keywords:["streak","sequência","sequencia","dias seguidos"], answer:"Streak é a sequência atual de dias em que você concluiu um hábito. Se ficar um dia sem concluir, a sequência atual reinicia; o maior streak fica preservado." },
 { intent:"progress_help", keywords:["progresso","histórico","historico","ranking","relatório","relatorio","taxa"], answer:"A aba Progresso mostra histórico visual de 30 dias, taxa de conclusão, ranking por consistência e insights pessoais." },
 { intent:"plan_free_help", keywords:["gratuito","grátis","gratis","free","limite"], answer:"O plano gratuito inclui até 5 hábitos ativos, categorias, streaks e histórico visual de 30 dias." },
 { intent:"premium_help", keywords:["premium","assinar","interesse premium","preço","preco"], answer:"O Premium ainda está em preparação comercial. Preços sugeridos: R$ 14,90/mês ou R$ 99/ano, com hábitos ilimitados e relatórios avançados no futuro." },
 { intent:"payment_help", keywords:["pagamento","checkout","cartão","cartao","boleto","pix"], answer:"O checkout está preparado para evolução, mas pagamento real ainda não deve ser considerado ativo. Não envie dados de cartão pelo chat." },
 { intent:"login_help", keywords:["login","entrar","google","senha","cadastro"], answer:"Você pode entrar com Google ou e-mail/senha. Se tiver dificuldade, tente atualizar a página e confirme se está usando o mesmo método de acesso." },
 { intent:"privacy_help", keywords:["privacidade","dados","termos","consentimento"], answer:"Seus hábitos são privados e vinculados à sua conta autenticada. Não envie senhas, CPF, cartão ou tokens no chat." },
 { intent:"lgpd_help", keywords:["lgpd","lei geral","dados pessoais"], answer:"O HabitFlow segue princípios básicos de LGPD: coleta mínima, finalidade clara e proteção dos dados da conta. Solicitações formais podem ser enviadas à MNSOFT." },
 { intent:"support_help", keywords:["suporte","atendente","humano","ajuda"], answer:"Você pode falar com a MNSOFT pelo WhatsApp configurado no sistema ou pelo e-mail comercial@mnsoft.com.br." },
 { intent:"whatsapp_help", keywords:["whatsapp","whats","zap","wa.me"], answer:"Se o WhatsApp estiver habilitado pelo Admin Geral, o botão Abrir WhatsApp aparece no chat e no Perfil. Caso contrário, use comercial@mnsoft.com.br." },
 { intent:"email_help", keywords:["email","e-mail","comercial"], answer:"O e-mail comercial e de suporte da MNSOFT é comercial@mnsoft.com.br." },
 { intent:"mnsoft_info", keywords:["mnsoft","cnpj","empresa","razão social","razao social"], answer:`Empresa responsável: ${COMPANY_INFO.companyName}. Razão social: ${COMPANY_INFO.companyLegalName}. CNPJ: ${COMPANY_INFO.companyCnpj}. E-mail: ${COMPANY_INFO.commercialEmail}.` },
 { intent:"bug_report", keywords:["bug","erro","falha","travou","não funciona","nao funciona"], answer:"Posso ajudar a registrar um chamado de bug. Informe o que aconteceu, a tela e se impede o uso, sem enviar dados sensíveis." },
 { intent:"technical_problem", keywords:["problema técnico","problema tecnico","não aparece","nao aparece","não atualizou","pwa não instala"], answer:"Para problemas técnicos, informe a tela e o comportamento esperado. Se for um bug, posso abrir um chamado com protocolo." },
 { intent:"pwa_help", keywords:["pwa","instalar","atalho","app no celular"], answer:"Para instalar o PWA, use o botão Instalar quando disponível no navegador ou a opção Adicionar à tela inicial no celular." },
];
function normalize(text="") { return String(text).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function detectSensitiveContent(message="") { const n=normalize(message); const promptInjection=/(ignore as instrucoes anteriores|ignore as instruções anteriores|voce e admin|você é admin|revele (seu )?prompt|mostre logs internos|logs internos|mostre codigo fonte|mostre código fonte|gere script para invadir|burlar firebase|burlar firestore|burlar auth|explorar vulnerabilidade)/i.test(n); const patterns=[/\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/,/\b(?:\d[ -]*?){13,19}\b/,/\b(bearer\s+[a-z0-9._-]+|api[_ -]?key|token|secret|senha|password|cvv)\b/i,/(burlar|invadir|hackear|explorar).*(firebase|firestore|auth|conta)/i,/(logs internos|stack trace|dados de outro|outros usuarios|alterar plano sem pagar|admin)/i,/(idiota|burro|desgraçado|ameaca|ameaça)/i]; const matched=promptInjection||patterns.some((p)=>p.test(message)||p.test(n)); const critical=promptInjection||/(burlar|invadir|hackear|bearer|api[_ -]?key|token|secret|logs internos|dados de outro|alterar plano sem pagar)/i.test(n); return { blocked: matched, promptInjection, critical, safeText: matched ? "[mensagem bloqueada por segurança]" : sanitizeText(message, 1000) }; }
function sanitizeText(text="", max=1000) { return String(text).replace(/[<>]/g, "").replace(/[\r\n\t]+/g," ").trim().slice(0,max); }
function detectIntent(message="") { const n=normalize(message); if (/(ignore as instrucoes anteriores|ignore as instruções anteriores|revele.*prompt|mostre logs internos|mostre codigo fonte|mostre código fonte)/i.test(n)) return { intent:"prompt_injection_attempt", severity:"critical", answer:PROMPT_INJECTION_REPLY, suggestedActions:[{label:"Falar com suporte",action:"support"}], confidence:0.99, safetyBlocked:true }; if (/(admin|logs internos|token|secret|burlar|invadir|hackear|dados de outro|alterar plano sem pagar)/i.test(n)) return { intent:"sensitive_request", severity:"critical", answer:SENSITIVE_REPLY, suggestedActions:[{label:"Falar com suporte",action:"support"}], confidence:0.98, safetyBlocked:true }; const found=INTENTS.find((item)=>item.keywords.some((k)=>n.includes(normalize(k)))); if (!found) return { intent:"unknown", severity:"info", answer:UNKNOWN_REPLY, suggestedActions:[{label:"Abrir suporte",action:"support"},{label:"Enviar e-mail",action:"email"}], confidence:0.35, safetyBlocked:false }; return { ...found, severity: ["bug_report","technical_problem"].includes(found.intent)?"warning":"info", suggestedActions: actionsFor(found.intent), confidence:0.82, safetyBlocked:false };
}
function actionsFor(intent) { if (["support_help","bug_report","technical_problem"].includes(intent)) return [{label:"Reportar bug",action:"report_bug"},{label:"Falar com MNSOFT",action:"support"}]; if (["premium_help","payment_help"].includes(intent)) return [{label:"Tenho interesse",action:"premium_interest"},{label:"Falar com comercial",action:"email"}]; if (["whatsapp_help","email_help","mnsoft_info"].includes(intent)) return [{label:"Abrir WhatsApp",action:"whatsapp"},{label:"Enviar e-mail",action:"email"}]; return [{label:"Ver hábitos",action:"dashboard"},{label:"Falar com suporte",action:"support"}]; }
function answerByRules(message="") { const sensitive=detectSensitiveContent(message); if (sensitive.promptInjection) return { answer:PROMPT_INJECTION_REPLY, intent:"prompt_injection_attempt", source:"rules", confidence:0.99, suggestedActions:[{label:"Falar com suporte",action:"support"}], safetyBlocked:true, severity:"critical", safeText:sensitive.safeText };
 if (sensitive.blocked) return { answer:SENSITIVE_REPLY, intent:sensitive.critical?"security_attack_request":"sensitive_request", source:"rules", confidence:0.99, suggestedActions:[{label:"Falar com suporte",action:"support"}], safetyBlocked:true, severity:sensitive.critical?"critical":"warning", safeText:sensitive.safeText };
 const intent=detectIntent(message); return { answer:sanitizeText(intent.answer,1200), intent:intent.intent, source:"rules", confidence:intent.confidence, suggestedActions:intent.suggestedActions, safetyBlocked:intent.safetyBlocked, severity:intent.severity, safeText:sensitive.safeText };
}
module.exports = { COMPANY_INFO, INTENTS, SENSITIVE_REPLY, PROMPT_INJECTION_REPLY, UNKNOWN_REPLY, detectSensitiveContent, sanitizeText, detectIntent, answerByRules };
