using HabitFlow.Domain;
using Microsoft.Extensions.DependencyInjection;

namespace HabitFlow.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddHabitFlowApplication(this IServiceCollection services)
    {
        services.AddSingleton<LogSanitizer>();
        services.AddSingleton<ProtocolGenerator>();
        services.AddSingleton<WhatsAppValidator>();
        services.AddSingleton<DocumentValidator>();
        services.AddSingleton<IUserFacingErrorMapper, UserFacingErrorMapper>();
        services.AddSingleton<FeedbackMapper>();
        services.AddHttpContextAccessor();
        services.AddScoped<IPasswordHasher, BCryptPasswordHasher>();
        services.AddScoped<IPasswordPolicy, PasswordPolicy>();
        services.AddScoped<PasswordResetTokenService>();
        services.AddScoped<PasswordRecoveryService>();
        services.AddScoped<PasswordResetService>();
        services.AddScoped<CreateSuperAdminHandler>();
        services.AddScoped<ResetSuperAdminPasswordHandler>();
        services.AddScoped<PromoteSuperAdminHandler>();
        services.AddScoped<CurrentUserContext>();
        services.AddScoped<CurrentTenantService>();
        services.AddScoped<HabitPolicy>();
        services.AddScoped<ProgressService>();
        services.AddScoped<HabitOccurrenceService>();
        services.AddScoped<ConsistencyService>();
        services.AddScoped<UserTimeZoneService>();
        services.AddScoped<ProgressCalendarService>();
        services.AddSingleton(TimeProvider.System);
        services.AddScoped<AdminAuthorizationService>();
        services.AddScoped<AuthService>();
        services.AddScoped<ClientAccountRegistrationService>();
        services.AddScoped<UserService>();
        services.AddScoped<UserInviteService>();
        services.AddScoped<ClientService>();
        services.AddScoped<HabitService>();
        services.AddScoped<ProgressSnapshotService>();
        services.AddScoped<GoalProgressCalculator>();
        services.AddScoped<GoalProgressEngine>();
        services.AddScoped<GoalHabitLinkService>();
        services.AddScoped<MilestoneEvaluationService>();
        services.AddScoped<CompleteHabitUseCase>();
        services.AddScoped<UndoHabitCompletionUseCase>();
        services.AddScoped<TodayDashboardService>();
        services.AddSingleton<HabitLibraryFallbackProvider>();
        services.AddScoped<HabitLibraryService>();
        services.AddSingleton<HabitTemplateCustomizationValidator>();
        services.AddScoped<CreateHabitFromTemplateUseCase>();
        services.AddScoped<HabitTemplateFavoriteService>();
        services.AddScoped<GuidedJourneyService>();
        services.AddScoped<HabitScheduleService>();
        services.AddScoped<NotificationService>();
        services.AddScoped<ReportService>();
        services.AddScoped<OnboardingService>();
        services.AddScoped<AuditService>();
        services.AddScoped<AdminAuditService>();
        services.AddScoped<SettingsService>();
        services.AddScoped<SupportService>();
        services.AddScoped<ProfileService>();
        services.AddScoped<UserUiPreferenceService>();
        services.AddScoped<AdminService>();
        services.AddScoped<AdminDashboardService>();
        services.AddScoped<AdminUserService>();
        services.AddScoped<AdminMetricsService>();
        services.AddScoped<AdminSupportService>();
        services.AddScoped<AdminLgpdService>();
        services.AddScoped<AdminAuditQueryService>();
        services.AddScoped<AdminExportService>();
        services.AddScoped<AdminBillingService>();
        services.AddScoped<AdminRiskService>();
        services.AddScoped<DatabaseDiagnosticsService>();
        services.AddScoped<WhatsAppService>();
        services.AddScoped<LgpdService>();
        services.AddScoped<BillingService>();
        services.AddScoped<BillingStatusJob>();
        services.AddScoped<EntitlementService>();
        services.AddScoped<PlanEntitlementService>();
        services.AddScoped<FeatureAccessService>();
        services.AddScoped<GoalService>();
        services.AddScoped<SuperAdminService>();
        services.AddSingleton<PaymentMetadataSanitizer>();
        services.AddScoped<PlanService>();
        services.AddScoped<SubscriptionService>();
        services.AddScoped<PremiumAccessService>();
        services.AddScoped<PaymentCheckoutService>();
        services.AddScoped<PaymentWebhookService>();
        services.AddScoped<PaymentAuditService>();
        services.AddScoped<FinancialDashboardService>();
        services.AddScoped<ClientOnboardingService>();
        services.AddScoped<ClientCommunicationService>();
        services.AddScoped<CustomerHealthService>();
        services.AddScoped<SchemaMigrationStatusService>();
        services.AddScoped<SuperAdminOperationalService>();
        services.AddHttpClient<IPaymentProviderService, MercadoPagoService>();
        services.AddHttpClient<TelegramService>();
        return services;
    }
}
