using HabitFlow.Domain; using HabitFlow.Shared; using Microsoft.Extensions.Logging; using System.Text.RegularExpressions;
namespace HabitFlow.Application;
public interface IPasswordHasher{string Hash(string password); bool Verify(string password,string hash);} public sealed class BCryptPasswordHasher:IPasswordHasher{public string Hash(string password)=>BCrypt.Net.BCrypt.HashPassword(password); public bool Verify(string password,string hash)=>BCrypt.Net.BCrypt.Verify(password,hash);} 
public sealed class HabitPolicy{public Result CanCreate(User user,int active)=>user.Plan=="Premium"||active<AppConstants.FreePlanHabitLimit?Result.Success():Result.Failure("plan.free_limit","Plano gratuito limitado a 5 hábitos ativos.");}
public sealed class ProgressService{public int CurrentStreak(IEnumerable<DateOnly> dates,DateOnly today){var set=dates.ToHashSet(); var streak=0; for(var d=today;set.Contains(d);d=d.AddDays(-1)) streak++; return streak;} public int BestStreak(IEnumerable<DateOnly> dates){var ordered=dates.Distinct().Order().ToList(); var best=0; var cur=0; DateOnly? prev=null; foreach(var d in ordered){cur=prev.HasValue&&d==prev.Value.AddDays(1)?cur+1:1; best=Math.Max(best,cur); prev=d;} return best;}}
public sealed class ProtocolGenerator{public string Generate(string prefix="HF")=>$"{prefix}-{DateTime.UtcNow:yyyyMMdd}-{Random.Shared.Next(100000,999999)}";}
public sealed class LogSanitizer{static readonly Regex Secret=new("(?i)(password|senha|token|cookie|secret)=([^&\\s]+)",RegexOptions.Compiled); public string Sanitize(string input)=>Secret.Replace(input,"$1=***");}
public sealed class WhatsAppValidator{public bool IsValid(string? number)=>!string.IsNullOrWhiteSpace(number)&&Regex.IsMatch(number,@"^\\+?[1-9]\\d{10,14}$");}
public sealed class AuthService(IUserRepository users,IPasswordHasher hasher,ILogger<AuthService> logger){public async Task<Result<User>> RegisterAsync(string name,string email,string password,CancellationToken ct=default){try{if(password.Length<8)return Result<User>.Failure("password.short","Senha deve ter ao menos 8 caracteres."); if(await users.GetByEmailAsync(email,ct) is not null)return Result<User>.Failure("email.exists","E-mail já cadastrado."); var now=DateTime.UtcNow; var user=new User(Guid.NewGuid(),name,email.ToLowerInvariant(),hasher.Hash(password),"User","Active","Free","Active",false,false,null,null,null,now,now); await users.CreateAsync(user,ct); return Result<User>.Success(user);}catch(Exception ex){logger.LogError(ex,"register_failed"); return Result<User>.Failure("auth.error","Não foi possível cadastrar.");}}}
