using System.Text;
using HabitFlow.Domain;
using HabitFlow.Shared;
using Microsoft.Extensions.Logging;

namespace HabitFlow.Application;

public sealed class AdminDashboardService(IAdminMetricsRepository repo, ILogger<AdminDashboardService> logger)
{
    public async Task<Result<AdminDashboardDto>> GetDashboardAsync(User adminUser, CancellationToken ct = default){try{return adminUser.Role!=UserRole.Admin?Result<AdminDashboardDto>.Failure("admin.denied","Acesso administrativo negado."):Result<AdminDashboardDto>.Success(await repo.GetDashboardAsync(ct));}catch(Exception ex){logger.LogError(ex,"Erro no dashboard admin");return Result<AdminDashboardDto>.Failure("admin.dashboard_error","Não foi possível carregar o dashboard.");}}
    public async Task<Result<SystemHealthSummary>> GetSystemHealthSummaryAsync(CancellationToken ct = default){try{var d=await repo.GetDashboardAsync(ct);return Result<SystemHealthSummary>.Success(new(d.SystemStatus,false,d.OpenLgpdRequests>0,d.CriticalErrors24h));}catch(Exception ex){logger.LogError(ex,"Erro no health admin");return Result<SystemHealthSummary>.Failure("admin.health_error","Não foi possível carregar saúde do sistema.");}}
}

public sealed class AdminUserService(IAdminUserRepository repo, AdminAuditService audit, ILogger<AdminUserService> logger)
{
    public async Task<Result<PagedResult<AdminUserListItem>>> SearchUsersAsync(AdminUserFilter filter, CancellationToken ct = default){try{var r=await repo.SearchUsersAsync(filter,ct);return Result<PagedResult<AdminUserListItem>>.Success(new(r.Items,r.TotalCount,Math.Max(1,filter.Page),Math.Clamp(filter.PageSize,1,100)));}catch(Exception ex){logger.LogError(ex,"Erro ao buscar usuários admin");return Result<PagedResult<AdminUserListItem>>.Failure("admin.users_error","Não foi possível buscar usuários.");}}
    public async Task<Result<AdminUserDetail>> GetUserDetailAsync(Guid userId, CancellationToken ct = default){try{var u=await repo.GetUserListItemAsync(userId,ct);return u is null?Result<AdminUserDetail>.Failure("admin.user_not_found","Usuário não encontrado."):Result<AdminUserDetail>.Success(new(u,await repo.GetNotesAsync(userId,ct),Array.Empty<object>(),Array.Empty<object>(),Array.Empty<object>()));}catch(Exception ex){logger.LogError(ex,"Erro ao detalhar usuário");return Result<AdminUserDetail>.Failure("admin.user_error","Não foi possível carregar usuário.");}}
    public async Task<Result> UpdateAccountStatusAsync(User adminUser, Guid userId, AccountStatus status, string reason, CancellationToken ct = default){if(string.IsNullOrWhiteSpace(reason))return Result.Failure("admin.reason_required","Motivo obrigatório."); if(adminUser.Id==userId && status is AccountStatus.Blocked or AccountStatus.Suspended)return Result.Failure("admin.self_block_denied","Admin não pode bloquear/suspender a própria conta sem confirmação explícita."); try{await repo.UpdateAccountStatusAsync(userId,status,reason.Trim(),ct);await audit.LogAsync(adminUser,$"user.status.{status}",reason,userId,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"Erro ao alterar status");return Result.Failure("admin.status_error","Não foi possível alterar status.");}}
    public async Task<Result> UpdateRiskStatusAsync(User adminUser, Guid userId, RiskStatus riskStatus, string reason, CancellationToken ct = default){if((riskStatus==RiskStatus.Suspicious||riskStatus==RiskStatus.Watchlist)&&string.IsNullOrWhiteSpace(reason))return Result.Failure("admin.reason_required","Motivo obrigatório para risco."); try{await repo.UpdateRiskStatusAsync(userId,riskStatus,reason,ct);await audit.LogAsync(adminUser,$"user.risk.{riskStatus}",reason,userId,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"Erro ao alterar risco");return Result.Failure("admin.risk_error","Não foi possível alterar risco.");}}
    public async Task<Result> UpdatePlanAsync(User adminUser, Guid userId, UserPlan plan, PlanStatus planStatus, string reason, CancellationToken ct = default){if(string.IsNullOrWhiteSpace(reason))return Result.Failure("admin.reason_required","Motivo obrigatório para alteração de plano."); try{await repo.UpdatePlanAsync(userId,plan,planStatus,reason.Trim(),ct);await audit.LogAsync(adminUser,$"user.plan.{plan}.{planStatus}",reason,userId,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"Erro ao alterar plano");return Result.Failure("admin.plan_error","Não foi possível alterar plano.");}}
    public async Task<Result> AddAdminNoteAsync(User adminUser, Guid userId, string note, CancellationToken ct = default){if(string.IsNullOrWhiteSpace(note))return Result.Failure("admin.note_required","Nota obrigatória."); try{await repo.AddNoteAsync(new(Guid.NewGuid(),userId,adminUser.Id,adminUser.Email,note.Trim(),DateTime.UtcNow),ct);await audit.LogAsync(adminUser,"user.note.added",null,userId,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"Erro ao adicionar nota");return Result.Failure("admin.note_error","Não foi possível adicionar nota.");}}
    public async Task<Result<IReadOnlyList<AdminUserNote>>> GetAdminNotesAsync(Guid userId, CancellationToken ct = default){try{return Result<IReadOnlyList<AdminUserNote>>.Success(await repo.GetNotesAsync(userId,ct));}catch(Exception ex){logger.LogError(ex,"Erro notas");return Result<IReadOnlyList<AdminUserNote>>.Failure("admin.notes_error","Não foi possível carregar notas.");}}
}

public sealed class AdminMetricsService(IAdminMetricsRepository repo, ILogger<AdminMetricsService> logger){public async Task<Result<GlobalMetrics>> GetGlobalMetricsAsync(CancellationToken ct=default){try{return Result<GlobalMetrics>.Success(await repo.GetGlobalMetricsAsync(ct));}catch(Exception ex){logger.LogError(ex,"metrics");return Result<GlobalMetrics>.Failure("metrics.error","Erro em métricas.");}} public async Task<Result<CommercialFunnel>> GetCommercialFunnelAsync(CancellationToken ct=default){try{return Result<CommercialFunnel>.Success(await repo.GetCommercialFunnelAsync(ct));}catch(Exception ex){logger.LogError(ex,"funnel");return Result<CommercialFunnel>.Failure("funnel.error","Erro no funil.");}} public async Task<Result<PagedResult<PremiumLead>>> GetPremiumLeadsAsync(AdminUserFilter f,CancellationToken ct=default){try{var r=await repo.GetPremiumLeadsAsync(f,ct);return Result<PagedResult<PremiumLead>>.Success(new(r.Items,r.TotalCount,f.Page,f.PageSize));}catch(Exception ex){logger.LogError(ex,"leads");return Result<PagedResult<PremiumLead>>.Failure("leads.error","Erro em leads.");}} public async Task<Result<FinancialSummary>> GetFinancialSummaryAsync(CancellationToken ct=default){try{return Result<FinancialSummary>.Success(await repo.GetFinancialSummaryAsync(ct));}catch(Exception ex){logger.LogError(ex,"finance");return Result<FinancialSummary>.Failure("finance.error","Erro financeiro.");}}}
public sealed class AdminSupportService(IAdminSupportRepository repo, AdminAuditService audit, ILogger<AdminSupportService> logger){public async Task<Result<PagedResult<object>>> SearchTicketsAsync(SupportTicketFilter f,CancellationToken ct=default){try{var r=await repo.SearchTicketsAsync(f,ct);return Result<PagedResult<object>>.Success(new(r.Items,r.TotalCount,f.Page,f.PageSize));}catch(Exception ex){logger.LogError(ex,"tickets");return Result<PagedResult<object>>.Failure("support.error","Erro em suporte.");}} public async Task<Result<object?>> GetTicketDetailAsync(Guid id,CancellationToken ct=default){try{return Result<object?>.Success(await repo.GetTicketDetailAsync(id,ct));}catch(Exception ex){logger.LogError(ex,"ticket");return Result<object?>.Failure("support.detail_error","Erro no ticket.");}} public async Task<Result> UpdateTicketStatusAsync(User admin,Guid id,string status,string message,CancellationToken ct=default){try{await repo.UpdateTicketStatusAsync(id,status,message,ct);await audit.LogAsync(admin,$"support.status.{status}",message,id,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"ticket status");return Result.Failure("support.update_error","Erro ao atualizar ticket.");}}}
public sealed class AdminLgpdService(IAdminLgpdRepository repo, AdminAuditService audit, ILogger<AdminLgpdService> logger){public async Task<Result<PagedResult<object>>> SearchRequestsAsync(LgpdRequestFilter f,CancellationToken ct=default){try{var r=await repo.SearchRequestsAsync(f,ct);return Result<PagedResult<object>>.Success(new(r.Items,r.TotalCount,f.Page,f.PageSize));}catch(Exception ex){logger.LogError(ex,"lgpd");return Result<PagedResult<object>>.Failure("lgpd.error","Erro LGPD.");}} public async Task<Result> UpdateRequestStatusAsync(User admin,Guid id,string status,string notes,CancellationToken ct=default){try{await repo.UpdateRequestStatusAsync(id,status,notes,ct);await audit.LogAsync(admin,$"lgpd.status.{status}",notes,id,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"lgpd status");return Result.Failure("lgpd.update_error","Erro ao atualizar LGPD.");}}}
public sealed class AdminAuditQueryService(IAdminAuditQueryRepository repo,AdminAuditService audit,ILogger<AdminAuditQueryService> logger){public async Task<Result<PagedResult<object>>> SearchSystemLogsAsync(AuditLogFilter f,CancellationToken ct=default){try{var r=await repo.SearchSystemLogsAsync(f,ct);return Result<PagedResult<object>>.Success(new(r.Items,r.TotalCount,f.Page,f.PageSize));}catch(Exception ex){logger.LogError(ex,"system logs");return Result<PagedResult<object>>.Failure("logs.error","Erro em logs.");}} public async Task<Result<PagedResult<object>>> SearchAdminLogsAsync(AuditLogFilter f,CancellationToken ct=default){try{var r=await repo.SearchAdminLogsAsync(f,ct);return Result<PagedResult<object>>.Success(new(r.Items,r.TotalCount,f.Page,f.PageSize));}catch(Exception ex){logger.LogError(ex,"admin logs");return Result<PagedResult<object>>.Failure("logs.error","Erro em auditoria.");}} public async Task<Result> MarkSystemLogAsReadAsync(User admin,Guid id,CancellationToken ct=default){try{await repo.MarkSystemLogAsReadAsync(id,ct);await audit.LogAsync(admin,"system_log.read",null,id,null,ct);return Result.Success();}catch(Exception ex){logger.LogError(ex,"read log");return Result.Failure("logs.read_error","Erro ao marcar lido.");}}}
public sealed class AdminExportService(IAdminExportRepository repo, AdminAuditService audit, ILogger<AdminExportService> logger){public static string SanitizeCsvCell(string? v){if(string.IsNullOrEmpty(v))return string.Empty; var s=v.Replace("\r"," ").Replace("\n"," "); return "=+-@".Contains(s[0])?"'"+s:s;} private async Task<Result<byte[]>> ExportAsync(User admin,string type,CancellationToken ct){try{var csv="tipo,gerado_em\n"+SanitizeCsvCell(type)+","+DateTime.UtcNow.ToString("O")+"\n";await repo.AddAsync(new(Guid.NewGuid(),admin.Id,admin.Email,type,$"{type}.csv","{}",1,DateTime.UtcNow),ct);await audit.LogAsync(admin,$"export.{type}","Exportação CSV",null,null,ct);return Result<byte[]>.Success(Encoding.UTF8.GetBytes(csv));}catch(Exception ex){logger.LogError(ex,"export {Type}",type);return Result<byte[]>.Failure("export.error","Erro ao exportar CSV.");}} public Task<Result<byte[]>> ExportUsersCsvAsync(User a,AdminUserFilter f,CancellationToken ct=default)=>ExportAsync(a,"users",ct); public Task<Result<byte[]>> ExportPremiumLeadsCsvAsync(User a,AdminUserFilter f,CancellationToken ct=default)=>ExportAsync(a,"leads",ct); public Task<Result<byte[]>> ExportSupportTicketsCsvAsync(User a,SupportTicketFilter f,CancellationToken ct=default)=>ExportAsync(a,"support",ct); public Task<Result<byte[]>> ExportLgpdRequestsCsvAsync(User a,LgpdRequestFilter f,CancellationToken ct=default)=>ExportAsync(a,"lgpd",ct); public Task<Result<byte[]>> ExportSystemLogsCsvAsync(User a,AuditLogFilter f,CancellationToken ct=default)=>ExportAsync(a,"system-logs",ct); public Task<Result<byte[]>> ExportAdminAuditCsvAsync(User a,AuditLogFilter f,CancellationToken ct=default)=>ExportAsync(a,"admin-audit",ct);}
public sealed class AdminBillingService(IAdminBillingRepository repo, ILogger<AdminBillingService> logger){public async Task<Result<FinancialSummary>> GetFinancialSummaryAsync(CancellationToken ct=default){try{return Result<FinancialSummary>.Success(await repo.GetFinancialSummaryAsync(ct));}catch(Exception ex){logger.LogError(ex,"billing");return Result<FinancialSummary>.Failure("billing.error","Erro financeiro.");}}}
public sealed class AdminRiskService(AdminUserService users){public Task<Result> MarkAsync(User admin,Guid userId,RiskStatus risk,string reason,CancellationToken ct=default)=>users.UpdateRiskStatusAsync(admin,userId,risk,reason,ct);}
