\i database/migrations/001_create_schema.sql
\i database/migrations/002_create_users.sql
\i database/migrations/003_create_habits.sql
\i database/migrations/004_create_habit_completions.sql
\i database/migrations/005_create_support.sql
\i database/migrations/006_create_audit.sql
\i database/migrations/007_create_settings.sql
\i database/migrations/008_create_lgpd.sql
\i database/migrations/009_create_billing.sql
\i database/migrations/010_create_indexes.sql
\i database/migrations/011_seed_initial_settings.sql
\i database/migrations/012_habit_recurrence_reports_notifications.sql
\i database/migrations/013_admin_operacional.sql
\i database/migrations/014_windows_iis_operations.sql
\i database/migrations/015_schema_hardening.sql
\i database/migrations/016_premium_billing.sql
\i database/migrations/017_habit_templates_guided_journey.sql
\i database/migrations/018_user_ui_preferences_accessibility.sql
\i database/migrations/019_notifications_feedback_preferences.sql
\i database/migrations/020_popup_preferences.sql
\i database/migrations/021_clients_management.sql
\i database/migrations/022_users_clients_link.sql
\i database/migrations/023_clients_cpf_cnpj_superadmin.sql
\i database/migrations/024_superadmin_billing_entitlements.sql
\i database/migrations/025_tenant_isolation_client_id.sql
\i database/migrations/026_backfill_client_id.sql
\i database/migrations/027_user_invites.sql
\i database/migrations/028_client_onboarding.sql
\i database/migrations/029_operational_completeness_v61.sql

\i database/migrations/030_client_registration_cpf_cnpj_real_flow.sql
\i database/migrations/031_registration_claims_onboarding_quality.sql
\i database/migrations/032_parameterized_plans_rbac_effective_access.sql
\i database/migrations/033_plan_prices_features.sql
\i database/migrations/034_roles_permissions.sql
\i database/migrations/035_effective_plan_payment_restrictions.sql
\i database/migrations/036_personal_goals.sql
\i database/migrations/037_consistency_milestones.sql
\i database/migrations/038_reminders.sql
\i database/migrations/039_shared_routines.sql
\i database/migrations/040_product_events_privacy.sql
\i database/migrations/041_scheduler_locking_idempotency.sql
\i database/migrations/042_sharing_privacy_consent.sql
\i database/migrations/043_goal_progress_completion.sql
\i database/migrations/044_report_snapshots_analytics.sql
\i database/migrations/045_pwa_product_events_hardening.sql

\i database/migrations/046_progress_history_days_limit.sql
