\i database/migrations/001_create_schema.sql
\i database/migrations/002_create_users.sql
\i database/migrations/003_create_habits.sql
\i database/migrations/004_create_habit_completions.sql
\i database/migrations/005_create_support.sql
\i database/migrations/006_create_audit.sql
\i database/migrations/007_create_settings.sql
\i database/migrations/008_create_lgpd.sql
\i database/migrations/009_create_billing.sql
\i database/migrations/010_create_indexes.sql
\i database/migrations/011_seed_initial_settings.sql
\i database/migrations/012_habit_recurrence_reports_notifications.sql
\i database/migrations/013_admin_operacional.sql
\i database/migrations/014_windows_iis_operations.sql
\i database/migrations/015_schema_hardening.sql
\i database/migrations/016_premium_billing.sql
\i database/migrations/017_habit_templates_guided_journey.sql
\i database/migrations/018_user_ui_preferences_accessibility.sql
\i database/migrations/019_notifications_feedback_preferences.sql
\i database/migrations/020_popup_preferences.sql
\i database/migrations/021_clients_management.sql
\i database/migrations/022_users_clients_link.sql
\i database/migrations/023_clients_cpf_cnpj_superadmin.sql
\i database/migrations/024_superadmin_billing_entitlements.sql
\i database/migrations/025_tenant_isolation_client_id.sql
\i database/migrations/026_backfill_client_id.sql
\i database/migrations/027_user_invites.sql
\i database/migrations/028_client_onboarding.sql
\i database/migrations/029_operational_completeness_v61.sql

\i database/migrations/030_client_registration_cpf_cnpj_real_flow.sql
\i database/migrations/031_registration_claims_onboarding_quality.sql
\i database/migrations/032_parameterized_plans_rbac_effective_access.sql
\i database/migrations/033_plan_prices_features.sql
\i database/migrations/034_roles_permissions.sql
\i database/migrations/035_effective_plan_payment_restrictions.sql
\i database/migrations/036_personal_goals.sql
\i database/migrations/037_consistency_milestones.sql
\i database/migrations/038_reminders.sql
\i database/migrations/039_shared_routines.sql
\i database/migrations/040_product_events_privacy.sql
\i database/migrations/041_scheduler_locking_idempotency.sql
\i database/migrations/042_sharing_privacy_consent.sql
\i database/migrations/043_goal_progress_completion.sql
\i database/migrations/044_report_snapshots_analytics.sql
\i database/migrations/045_pwa_product_events_hardening.sql

\i database/migrations/046_progress_history_days_limit.sql
\i database/migrations/047_schema_migration_governance.sql
\i database/migrations/048_password_recovery_transactional_email.sql
\i database/migrations/049_billing_communication_rule_seed_integrity.sql
\i database/migrations/050_goal_progress_activation_core.sql
\i database/migrations/051_system_settings_contract.sql
\i database/migrations/052_library_v2_onboarding.sql
\i database/migrations/053_persistent_onboarding_drafts.sql
\i database/migrations/054_onboarding_engagement_notification_center.sql
\i database/migrations/055_routine_planner_weekly_review.sql
\i database/migrations/056_secure_admin_honest_plans_legal_privacy.sql
\i database/migrations/057_legal_document_immutability.sql
\i database/migrations/058_user_sessions.sql
\i database/migrations/059_superadmin_mfa.sql
\i database/migrations/060_public_privacy_notice.sql
\i database/migrations/061_habit_lifecycle.sql
\i database/migrations/062_product_tips.sql
\i database/migrations/063_account_privacy_center.sql
\i database/migrations/064_v6121_commercial_plan_integrity.sql
\i database/migrations/065_v6123_crud_contract_backfill.sql
\i database/migrations/066_lgpd_privacy_schema_repair.sql
\i database/migrations/067_reminder_dispatch_runtime.sql
\i database/migrations/068_reminder_runtime_integrity.sql
\i database/migrations/069_v6165_intelligent_onboarding_challenges.sql
\i database/migrations/070_v6166_premium_reports.sql
\i database/migrations/071_v6167_secure_multitenant_billing.sql
\i database/migrations/072_v6168_pwa_push_offline.sql
\i database/migrations/073_v6169_secure_assistance_support.sql
\i database/migrations/074_v6170_saas_admin_lgpd.sql
\i database/migrations/075_v6171_release_candidate_integrity.sql
\i database/migrations/076_v6173_healthy_gamification.sql
\i database/migrations/077_v6177_mobile_pwa_notification_preferences.sql
\i database/migrations/078_v6179_real_billing_commercial.sql
\i database/migrations/079_v6180_corporate_programs.sql
\i database/migrations/080_v6182_safe_contextual_assistant.sql
\i database/migrations/081_v6188_premium_gamification.sql
\i database/migrations/082_v6190_security_lgpd_hardening.sql
\i database/migrations/083_v6191_public_integrations.sql
\i database/migrations/084_v6192_superadmin_tenant_governance.sql
\i database/migrations/085_v6194_operations_center.sql
\i database/migrations/086_v6195_superadmin_bootstrap.sql
\i database/migrations/087_v6196_ai_multi_provider_assistant.sql
\i database/migrations/088_v6193_support_center.sql
\i database/migrations/089_v6196_saas_team_enterprise_catalog.sql
\i database/migrations/090_atomic_account_invites_capacity.sql
\i database/migrations/091_account_people_join_date.sql
\i database/migrations/092_market_implemented_user_invites.sql
\i database/migrations/093_restore_schema_contract_constraints.sql
\i database/migrations/094_v6197_ai_admin_usage.sql
