using HabitFlow.Application;
using HabitFlow.Domain;

namespace HabitFlow.Infrastructure;

internal static class AdminPaging { public static (int Page,int Size,int Offset) Normalize(int page,int size){var p=Math.Max(1,page); var s=Math.Clamp(size<=0?20:size,1,100); return(p,s,(p-1)*s);} }

public sealed class AdminUserRepository(SqlExecutor db) : IAdminUserRepository
{
    private const string ListSql = @"select u.id, u.name, u.email, u.plan, u.plan_status, u.account_status, u.risk_status, u.wants_premium_notice,
        (select count(*)::int from habitflow.habits h where h.user_id=u.id and h.is_active=true) active_habits,
        (select count(*)::int from habitflow.habit_completions c join habitflow.habits h on h.id=c.habit_id where h.user_id=u.id) completions,
        u.last_login_at, u.created_at from habitflow.users u";
    public async Task<(IReadOnlyList<AdminUserListItem> Items, int TotalCount)> SearchUsersAsync(AdminUserFilter f, CancellationToken ct = default)
    {
        var p=AdminPaging.Normalize(f.Page,f.PageSize); var where=" where (@Search is null or u.name ilike @Like or u.email ilike @Like) and (@Plan is null or u.plan=@Plan) and (@AccountStatus is null or u.account_status=@AccountStatus) and (@RiskStatus is null or u.risk_status=@RiskStatus) and (@WantsPremiumNotice is null or u.wants_premium_notice=@WantsPremiumNotice) and (@CreatedFrom is null or u.created_at>=@CreatedFrom) and (@CreatedTo is null or u.created_at<=@CreatedTo) and (@LastLoginFrom is null or u.last_login_at>=@LastLoginFrom) and (@LastLoginTo is null or u.last_login_at<=@LastLoginTo)";
        var args=new { f.Search, Like="%"+f.Search+"%", Plan=f.Plan?.ToString(), AccountStatus=f.AccountStatus?.ToString(), RiskStatus=f.RiskStatus?.ToString(), f.WantsPremiumNotice, f.CreatedFrom, f.CreatedTo, f.LastLoginFrom, f.LastLoginTo, Limit=p.Size, Offset=p.Offset };
        var items=(await db.QueryAsync<AdminUserListItem>(ListSql+where+" order by u.created_at desc limit @Limit offset @Offset", args, ct)).ToList();
        var count=await db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.users u"+where,args,ct);
        return (items,count);
    }
    public Task<AdminUserListItem?> GetUserListItemAsync(Guid userId, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<AdminUserListItem>(ListSql+" where u.id=@userId", new { userId }, ct);
    public Task UpdateAccountStatusAsync(Guid userId, AccountStatus status, string reason, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.users set account_status=@status, blocked_at=case when @status='Blocked' then now() else blocked_at end, blocked_reason=case when @status='Blocked' then @reason else blocked_reason end, suspended_at=case when @status='Suspended' then now() else suspended_at end, suspended_reason=case when @status='Suspended' then @reason else suspended_reason end, last_admin_review_at=now(), updated_at=now() where id=@userId", new { userId, status=status.ToString(), reason }, ct);
    public Task UpdateRiskStatusAsync(Guid userId, RiskStatus status, string reason, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.users set risk_status=@status, last_admin_review_at=now(), updated_at=now() where id=@userId", new { userId, status=status.ToString(), reason }, ct);
    public Task UpdatePlanAsync(Guid userId, UserPlan plan, PlanStatus planStatus, string reason, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.users set plan=@plan, plan_status=@planStatus, last_admin_review_at=now(), updated_at=now() where id=@userId", new { userId, plan=plan.ToString(), planStatus=planStatus.ToString(), reason }, ct);
    public Task AddNoteAsync(AdminUserNote n, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.admin_user_notes(id,user_id,admin_user_id,admin_email,note,created_at) values(@Id,@UserId,@AdminUserId,@AdminEmail,@Note,@CreatedAt); update habitflow.users set admin_notes_count=admin_notes_count+1 where id=@UserId", n, ct);
    public async Task<IReadOnlyList<AdminUserNote>> GetNotesAsync(Guid userId, CancellationToken ct = default) => (await db.QueryAsync<AdminUserNote>("select id,user_id,admin_user_id,admin_email,note,created_at from habitflow.admin_user_notes where user_id=@userId order by created_at desc limit 100", new { userId }, ct)).ToList();
}

public sealed class AdminMetricsRepository(SqlExecutor db) : IAdminMetricsRepository, IAdminBillingRepository
{
    public async Task<AdminDashboardDto> GetDashboardAsync(CancellationToken ct = default) => new(await Scalar("select count(*) from habitflow.users",ct),await Scalar("select count(*) from habitflow.users where last_activity_at>=now()-interval '7 days'",ct),await Scalar("select count(*) from habitflow.users where created_at>=now()-interval '7 days'",ct),await Scalar("select count(*) from habitflow.habits where is_active=true",ct),await Scalar("select count(*) from habitflow.habit_completions where completed_at>=now()-interval '7 days'",ct),await Scalar("select count(*) from habitflow.support_tickets where status in ('Open','InProgress')",ct),await Scalar("select count(*) from habitflow.lgpd_requests where status not in ('Concluded','Rejected','Canceled')",ct),0,await Scalar("select count(*) from habitflow.users where wants_premium_notice=true or plan='Premium'",ct),0m,"Operacional",Array.Empty<AdminUserListItem>());
    public async Task<GlobalMetrics> GetGlobalMetricsAsync(CancellationToken ct = default) => new(await Scalar("select count(*) from habitflow.users",ct),await Scalar("select count(*) from habitflow.habits",ct),await Scalar("select count(*) from habitflow.habit_completions",ct),await Scalar("select count(*) from habitflow.users where plan='Premium'",ct));
    public async Task<CommercialFunnel> GetCommercialFunnelAsync(CancellationToken ct = default) => new(await Scalar("select count(*) from habitflow.users",ct),await Scalar("select count(distinct user_id) from habitflow.habits",ct),await Scalar("select count(*) from habitflow.users where last_activity_at>=now()-interval '7 days'",ct),await Scalar("select count(*) from habitflow.users u where u.plan='Free' and (select count(*) from habitflow.habits h where h.user_id=u.id)>=5",ct),await Scalar("select count(*) from habitflow.users where wants_premium_notice=true",ct),await Scalar("select count(*) from habitflow.users where plan='Premium' and plan_status in ('Active','Trial')",ct));
    public async Task<(IReadOnlyList<PremiumLead> Items, int TotalCount)> GetPremiumLeadsAsync(AdminUserFilter f, CancellationToken ct = default){var p=AdminPaging.Normalize(f.Page,f.PageSize); var sql="select u.id user_id,u.name,u.email,case when u.wants_premium_notice then 'Solicitou aviso Premium' else 'Uso elevado no plano Free' end reason,(select count(*)::int from habitflow.habits h where h.user_id=u.id and h.is_active=true) active_habits,(select count(*)::int from habitflow.habit_completions c join habitflow.habits h on h.id=c.habit_id where h.user_id=u.id and c.completed_at>=now()-interval '30 days') completions30_days,u.last_login_at,u.plan from habitflow.users u where u.wants_premium_notice=true or u.plan='Premium' order by u.last_login_at desc nulls last limit @Limit offset @Offset"; return ((await db.QueryAsync<PremiumLead>(sql,new{Limit=p.Size,Offset=p.Offset},ct)).ToList(), (int)await Scalar("select count(*) from habitflow.users where wants_premium_notice=true or plan='Premium'",ct));}
    public async Task<FinancialSummary> GetFinancialSummaryAsync(CancellationToken ct = default){var leads=await Scalar("select count(*) from habitflow.users where wants_premium_notice=true",ct); var premium=await Scalar("select count(*) from habitflow.users where plan='Premium' and plan_status in ('Active','Trial')",ct); return new FinancialSummary(0m, leads*14.90m, leads*99.00m, premium, leads, Array.Empty<object>());} 
    private async Task<long> Scalar(string sql,CancellationToken ct)=> await db.QuerySingleOrDefaultAsync<long>(sql,null,ct);
}

public sealed class AdminExportRepository(SqlExecutor db) : IAdminExportRepository { public Task AddAsync(AdminExport e, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.admin_exports(id,admin_user_id,admin_email,export_type,file_name,filters,rows_count,created_at) values(@Id,@AdminUserId,@AdminEmail,@ExportType,@FileName,cast(@Filters as jsonb),@RowsCount,@CreatedAt)", e, ct); }
public sealed class AdminSupportRepository(SqlExecutor db) : IAdminSupportRepository { public async Task<(IReadOnlyList<object> Items, int TotalCount)> SearchTicketsAsync(SupportTicketFilter f, CancellationToken ct = default)=>( (await db.QueryAsync<object>("select * from habitflow.support_tickets order by created_at desc limit 50",null,ct)).ToList(),0); public Task<object?> GetTicketDetailAsync(Guid ticketId, CancellationToken ct = default)=>db.QuerySingleOrDefaultAsync<object>("select * from habitflow.support_tickets where id=@ticketId",new{ticketId},ct); public Task UpdateTicketStatusAsync(Guid ticketId,string status,string? message,CancellationToken ct=default)=>db.ExecuteAsync("update habitflow.support_tickets set status=@status, updated_at=now() where id=@ticketId",new{ticketId,status,message},ct); }
public sealed class AdminLgpdRepository(SqlExecutor db) : IAdminLgpdRepository { public async Task<(IReadOnlyList<object> Items, int TotalCount)> SearchRequestsAsync(LgpdRequestFilter f, CancellationToken ct = default)=>( (await db.QueryAsync<object>("select * from habitflow.lgpd_requests order by created_at desc limit 50",null,ct)).ToList(),0); public Task UpdateRequestStatusAsync(Guid requestId,string status,string? notes,CancellationToken ct=default)=>db.ExecuteAsync("update habitflow.lgpd_requests set status=@status, notes=@notes, updated_at=now() where id=@requestId",new{requestId,status,notes},ct); }
public sealed class AdminAuditQueryRepository(SqlExecutor db) : IAdminAuditQueryRepository { public async Task<(IReadOnlyList<object> Items, int TotalCount)> SearchSystemLogsAsync(AuditLogFilter f, CancellationToken ct = default)=>( (await db.QueryAsync<object>("select * from habitflow.system_audit_logs order by created_at desc limit 50",null,ct)).ToList(),0); public async Task<(IReadOnlyList<object> Items, int TotalCount)> SearchAdminLogsAsync(AuditLogFilter f, CancellationToken ct = default)=>( (await db.QueryAsync<object>("select * from habitflow.admin_audit_logs order by created_at desc limit 50",null,ct)).ToList(),0); public Task MarkSystemLogAsReadAsync(Guid logId, CancellationToken ct = default)=>db.ExecuteAsync("update habitflow.system_audit_logs set read_by_admin=true where id=@logId",new{logId},ct); }
