using HabitFlow.Domain;

namespace HabitFlow.Infrastructure;

public sealed class AssistanceRepository(SqlExecutor db) : IAssistanceRepository
{
    public async Task<Guid> GetOrCreateConversationAsync(Guid clientId, Guid userId, CancellationToken ct = default)
    {
        var id=await db.QuerySingleOrDefaultAsync<Guid?>("select id from habitflow.assistant_conversations where client_id=@clientId and user_id=@userId order by updated_at desc limit 1",new{clientId,userId},ct);
        if(id.HasValue)return id.Value; var created=Guid.NewGuid(); await db.ExecuteAsync("insert into habitflow.assistant_conversations(id,client_id,user_id,created_at,updated_at) values(@created,@clientId,@userId,now(),now())",new{created,clientId,userId},ct); return created;
    }
    public Task AddMessageAsync(AssistantMessage m,CancellationToken ct=default)=>db.ExecuteAsync("insert into habitflow.assistant_messages(id,client_id,user_id,conversation_id,role,message,sanitized_message,safety_status,provider,created_at,correlation_id) values(@Id,@ClientId,@UserId,@ConversationId,@Role,@Message,@SanitizedMessage,@SafetyStatus,@Provider,@CreatedAt,@CorrelationId); update habitflow.assistant_conversations set updated_at=now() where id=@ConversationId and client_id=@ClientId and user_id=@UserId",m,ct);
    public async Task<IReadOnlyList<AssistantMessage>> ListMessagesAsync(Guid clientId,Guid userId,Guid conversationId,CancellationToken ct=default)=>(await db.QueryAsync<AssistantMessage>("select id,client_id,user_id,conversation_id,role,message,sanitized_message,safety_status,provider,created_at,correlation_id from habitflow.assistant_messages where client_id=@clientId and user_id=@userId and conversation_id=@conversationId order by created_at",new{clientId,userId,conversationId},ct)).ToArray();
    public Task DeleteHistoryAsync(Guid clientId,Guid userId,CancellationToken ct=default)=>db.ExecuteAsync("delete from habitflow.assistant_conversations where client_id=@clientId and user_id=@userId",new{clientId,userId},ct);
    public async Task<SupportSettings> GetSupportSettingsAsync(CancellationToken ct=default)=>await db.QuerySingleOrDefaultAsync<SupportSettings>("select id,company_name,company_document,support_email,whatsapp_phone,default_message,business_hours,is_active,button_text,updated_at from habitflow.support_settings order by updated_at desc limit 1",null,ct) ?? new(Guid.Empty,"MNSOFT","18.160.057/0001-13","comercial@mnsoft.com.br",null,"Olá! Preciso de ajuda com o HabitFlow.","Segunda a sexta, 9h às 18h",true,"Falar com a MNSOFT",DateTime.UtcNow);
    public Task UpdateSupportSettingsAsync(SupportSettings s,CancellationToken ct=default)=>db.ExecuteAsync("insert into habitflow.support_settings(id,company_name,company_document,support_email,whatsapp_phone,default_message,business_hours,is_active,button_text,updated_at) values(@Id,@CompanyName,@CompanyDocument,@SupportEmail,@WhatsAppPhone,@DefaultMessage,@BusinessHours,@IsActive,@ButtonText,now()) on conflict(id) do update set company_name=excluded.company_name,company_document=excluded.company_document,support_email=excluded.support_email,whatsapp_phone=excluded.whatsapp_phone,default_message=excluded.default_message,business_hours=excluded.business_hours,is_active=excluded.is_active,button_text=excluded.button_text,updated_at=now()",s,ct);
    public Task CreateTicketAsync(SupportTicketDetail t,CancellationToken ct=default)=>db.ExecuteAsync("insert into habitflow.support_tickets_v2(id,client_id,user_id,protocol,category,status,subject,description,safe_context,created_at,updated_at,closed_at) values(@Id,@ClientId,@UserId,@Protocol,@Category,@Status,@Subject,@Description,@SafeContext,@CreatedAt,@UpdatedAt,@ClosedAt)",t,ct);
    public async Task<IReadOnlyList<SupportTicketDetail>> ListTicketsAsync(Guid clientId,Guid userId,bool admin,CancellationToken ct=default)=>(await db.QueryAsync<SupportTicketDetail>("select id,client_id,user_id,protocol,category,status,subject,description,safe_context,created_at,updated_at,closed_at from habitflow.support_tickets_v2 where client_id=@clientId and (@admin or user_id=@userId) order by updated_at desc",new{clientId,userId,admin},ct)).ToArray();
    public Task<SupportTicketDetail?> GetTicketAsync(Guid clientId,Guid userId,Guid ticketId,bool admin,CancellationToken ct=default)=>db.QuerySingleOrDefaultAsync<SupportTicketDetail>("select id,client_id,user_id,protocol,category,status,subject,description,safe_context,created_at,updated_at,closed_at from habitflow.support_tickets_v2 where id=@ticketId and client_id=@clientId and (@admin or user_id=@userId)",new{clientId,userId,ticketId,admin},ct);
    public Task AddTicketMessageAsync(SupportTicketMessage m,CancellationToken ct=default)=>db.ExecuteAsync("insert into habitflow.support_ticket_messages_v2(id,client_id,ticket_id,user_id,is_staff,message,created_at) select @Id,@ClientId,@TicketId,@UserId,@IsStaff,@Message,@CreatedAt where exists(select 1 from habitflow.support_tickets_v2 where id=@TicketId and client_id=@ClientId); update habitflow.support_tickets_v2 set status=case when @IsStaff then 'Responded' else 'InAnalysis' end,updated_at=now() where id=@TicketId and client_id=@ClientId and status<>'Closed'",m,ct);
    public async Task<IReadOnlyList<SupportTicketMessage>> ListTicketMessagesAsync(Guid clientId,Guid ticketId,CancellationToken ct=default)=>(await db.QueryAsync<SupportTicketMessage>("select id,client_id,ticket_id,user_id,is_staff,message,created_at from habitflow.support_ticket_messages_v2 where client_id=@clientId and ticket_id=@ticketId order by created_at",new{clientId,ticketId},ct)).ToArray();
    public Task UpdateTicketStatusAsync(Guid clientId,Guid ticketId,string status,DateTime? closedAt,CancellationToken ct=default)=>db.ExecuteAsync("update habitflow.support_tickets_v2 set status=@status,closed_at=@closedAt,updated_at=now() where id=@ticketId and client_id=@clientId",new{clientId,ticketId,status,closedAt},ct);
}
