using HabitFlow.Domain;

namespace HabitFlow.Infrastructure;

public sealed class HabitRepository(SqlExecutor db) : IHabitRepository
{
    internal const string Columns = HabitSql.Columns;

    public Task<int> CountActiveByUserAsync(Guid userId, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.habits where user_id = @userId and is_archived = false", new { userId }, ct)!;
    public async Task<IReadOnlyList<Habit>> ListByUserAsync(Guid userId, CancellationToken ct = default) => (await db.QueryAsync<Habit>("select " + Columns + " from habitflow.habits where user_id = @userId order by is_archived, sort_order, created_at desc", new { userId }, ct)).ToList();
    public async Task<IReadOnlyList<Habit>> ListAsync(Guid clientId, Guid userId, CancellationToken ct = default) => (await db.QueryAsync<Habit>("select " + Columns + " from habitflow.habits where client_id = @clientId and user_id = @userId order by is_archived, is_paused, sort_order, created_at desc", new { clientId, userId }, ct)).ToList();
    public async Task<IReadOnlyList<Habit>> ListActiveAsync(Guid clientId, Guid userId, CancellationToken ct = default) =>
        (await db.QueryAsync<Habit>("select " + Columns + " from habitflow.habits where client_id = @clientId and user_id = @userId and is_archived = false order by sort_order, created_at desc", new { clientId, userId }, ct)).ToList();
    public Task<Habit?> FindByIdempotencyKeyAsync(Guid clientId, Guid userId, Guid idempotencyKey, CancellationToken ct = default) =>
        db.QuerySingleOrDefaultAsync<Habit>("select " + Columns + " from habitflow.habits where client_id = @clientId and user_id = @userId and template_idempotency_key = @idempotencyKey limit 1", new { clientId, userId, idempotencyKey }, ct);
    public Task<Habit?> FindActiveBySourceTemplateAsync(Guid clientId, Guid userId, Guid templateId, bool includeVariations, CancellationToken ct = default) =>
        db.QuerySingleOrDefaultAsync<Habit>("select " + Columns + " from habitflow.habits where client_id = @clientId and user_id = @userId and source_template_id = @templateId and is_archived = false and (@includeVariations or is_template_variation = false) order by created_at limit 1", new { clientId, userId, templateId, includeVariations }, ct);
    public Task<int> CountActiveAsync(Guid clientId, Guid userId, CancellationToken ct = default) =>
        db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.habits where client_id = @clientId and user_id = @userId and is_archived = false", new { clientId, userId }, ct)!;
    public Task<Habit?> GetAsync(Guid clientId, Guid userId, Guid habitId, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<Habit>("select " + Columns + " from habitflow.habits where client_id = @clientId and user_id = @userId and id = @habitId", new { clientId, userId, habitId }, ct);
    public Task CreateAsync(Habit h, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.habits(id,user_id,name,color,category,is_archived,archived_at,created_at,updated_at,frequency_type,target_per_week,reminder_time,notes,sort_order,client_id,source_template_id,source_collection_id,objective_id,icon_code,difficulty,estimated_time_minutes,start_date,template_content_version,is_template_variation,template_idempotency_key,is_paused,paused_at) values(@Id,@UserId,@Name,@Color,@Category,@IsArchived,@ArchivedAt,@CreatedAt,@UpdatedAt,@FrequencyType,@TargetPerWeek,@ReminderTime,@Notes,@SortOrder,@ClientId,@SourceTemplateId,@SourceCollectionId,@ObjectiveId,@IconCode,@Difficulty,@EstimatedTimeMinutes,@StartDate,@TemplateContentVersion,@IsTemplateVariation,@TemplateIdempotencyKey,@IsPaused,@PausedAt)", new { h.Id, h.UserId, h.Name, h.Color, h.Category, h.IsArchived, h.ArchivedAt, h.CreatedAt, h.UpdatedAt, FrequencyType = h.FrequencyType.ToString(), h.TargetPerWeek, h.ReminderTime, h.Notes, h.SortOrder, h.ClientId, h.SourceTemplateId, h.SourceCollectionId, h.ObjectiveId, h.IconCode, Difficulty = h.Difficulty?.ToString(), h.EstimatedTimeMinutes, h.StartDate, h.TemplateContentVersion, h.IsTemplateVariation, h.TemplateIdempotencyKey, h.IsPaused, h.PausedAt }, ct);
    public async Task<bool> UpdateAsync(Guid clientId, Guid userId, Habit h, CancellationToken ct = default) => await db.ExecuteAsync("update habitflow.habits set name=@Name,color=@Color,category=@Category,is_archived=@IsArchived,archived_at=@ArchivedAt,is_paused=@IsPaused,paused_at=@PausedAt,updated_at=@UpdatedAt,frequency_type=@FrequencyType,target_per_week=@TargetPerWeek,reminder_time=@ReminderTime,notes=@Notes,sort_order=@SortOrder,objective_id=@ObjectiveId,icon_code=@IconCode,difficulty=@Difficulty,estimated_time_minutes=@EstimatedTimeMinutes where id=@Id and client_id=@clientId and user_id=@userId", new { h.Id, h.Name, h.Color, h.Category, h.IsArchived, h.ArchivedAt, h.IsPaused, h.PausedAt, h.UpdatedAt, FrequencyType = h.FrequencyType.ToString(), h.TargetPerWeek, h.ReminderTime, h.Notes, h.SortOrder, h.ObjectiveId, h.IconCode, Difficulty = h.Difficulty?.ToString(), h.EstimatedTimeMinutes, clientId, userId }, ct) > 0;
}

internal static class HabitSql
{
    // Keep this projection aligned with Habit's positional constructor. `visibility` is a legacy
    // database column and intentionally is not part of the domain contract.
    internal const string Columns = "id, user_id, name, color, category, is_archived, archived_at, created_at, updated_at, frequency_type, target_per_week, reminder_time, notes, sort_order, client_id, source_template_id, source_collection_id, objective_id, icon_code, difficulty, estimated_time_minutes, start_date, template_content_version, is_template_variation, template_idempotency_key, is_paused, paused_at";
    internal const string AliasedColumns = "h.id, h.user_id, h.name, h.color, h.category, h.is_archived, h.archived_at, h.created_at, h.updated_at, h.frequency_type, h.target_per_week, h.reminder_time, h.notes, h.sort_order, h.client_id, h.source_template_id, h.source_collection_id, h.objective_id, h.icon_code, h.difficulty, h.estimated_time_minutes, h.start_date, h.template_content_version, h.is_template_variation, h.template_idempotency_key, h.is_paused, h.paused_at";
}
