using HabitFlow.Domain;

namespace HabitFlow.Infrastructure;

public sealed class PlanRepository(SqlExecutor db) : IPlanRepository
{ private const string C = "id,code,name,description,price_monthly,price_yearly,currency,habit_limit,reports_enabled,advanced_reports_enabled,challenges_enabled,is_active,is_public,created_at,updated_at"; public async Task<IReadOnlyList<Plan>> GetPublicPlansAsync(CancellationToken ct = default) => (await db.QueryAsync<Plan>($"select {C} from habitflow.plans where is_active=true and is_public=true order by coalesce(price_monthly, price_yearly, 0)", null, ct)).ToList(); public Task<Plan?> GetByCodeAsync(string code, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<Plan>($"select {C} from habitflow.plans where code=@code", new { code }, ct); }

public sealed class SubscriptionRepository(SqlExecutor db) : ISubscriptionRepository
{ private const string C = "id,user_id,plan_code,status,billing_cycle,provider,provider_customer_id,provider_subscription_id,provider_payment_id,checkout_url,current_period_start,current_period_end,trial_ends_at,canceled_at,created_at,updated_at"; public Task<Subscription?> GetActiveOrLatestByUserIdAsync(Guid userId, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<Subscription>($"select {C} from habitflow.subscriptions where user_id=@userId order by case when status in ('Active','Trial','PastDue') then 0 else 1 end, created_at desc limit 1", new { userId }, ct); public Task<Subscription?> GetByIdAsync(Guid id, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<Subscription>($"select {C} from habitflow.subscriptions where id=@id", new { id }, ct); public Task<Subscription?> GetByProviderPaymentIdAsync(string providerPaymentId, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<Subscription>($"select {C} from habitflow.subscriptions where provider_payment_id=@providerPaymentId", new { providerPaymentId }, ct); public Task CreateAsync(Subscription s, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.subscriptions(id,user_id,plan_code,status,billing_cycle,provider,provider_customer_id,provider_subscription_id,provider_payment_id,checkout_url,current_period_start,current_period_end,trial_ends_at,canceled_at,created_at,updated_at) values(@Id,@UserId,@PlanCode,@Status::text,@BillingCycle::text,@Provider::text,@ProviderCustomerId,@ProviderSubscriptionId,@ProviderPaymentId,@CheckoutUrl,@CurrentPeriodStart,@CurrentPeriodEnd,@TrialEndsAt,@CanceledAt,@CreatedAt,@UpdatedAt)", s, ct); public Task UpdateAsync(Subscription s, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.subscriptions set plan_code=@PlanCode,status=@Status::text,billing_cycle=@BillingCycle::text,provider=@Provider::text,provider_customer_id=@ProviderCustomerId,provider_subscription_id=@ProviderSubscriptionId,provider_payment_id=@ProviderPaymentId,checkout_url=@CheckoutUrl,current_period_start=@CurrentPeriodStart,current_period_end=@CurrentPeriodEnd,trial_ends_at=@TrialEndsAt,canceled_at=@CanceledAt,updated_at=@UpdatedAt where id=@Id", s, ct); public Task UpdateCheckoutAsync(Guid id, string? checkoutUrl, string? providerSubscriptionId, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.subscriptions set checkout_url=@checkoutUrl, provider_subscription_id=@providerSubscriptionId, updated_at=now() where id=@id", new { id, checkoutUrl, providerSubscriptionId }, ct); public async Task<IReadOnlyList<Subscription>> ListByStatusAsync(SubscriptionStatus? status, CancellationToken ct = default) => (await db.QueryAsync<Subscription>($"select {C} from habitflow.subscriptions where @status is null or status=@status order by created_at desc", new { status = status?.ToString() }, ct)).ToList(); }

public sealed class PaymentTransactionRepository(SqlExecutor db) : IPaymentTransactionRepository
{ private const string C = "id,user_id,subscription_id,provider,provider_payment_id,provider_preference_id,event_type,status,amount,currency,raw_status,sanitized_metadata::text as sanitized_metadata,created_at,updated_at"; public Task CreateAsync(PaymentTransaction t, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.payment_transactions(id,user_id,subscription_id,provider,provider_payment_id,provider_preference_id,event_type,status,amount,currency,raw_status,sanitized_metadata,created_at,updated_at) values(@Id,@UserId,@SubscriptionId,@Provider::text,@ProviderPaymentId,@ProviderPreferenceId,@EventType,@Status::text,@Amount,@Currency,@RawStatus,@SanitizedMetadata::jsonb,@CreatedAt,@UpdatedAt)", t, ct); public async Task<IReadOnlyList<PaymentTransaction>> ListLatestAsync(int limit, CancellationToken ct = default) => (await db.QueryAsync<PaymentTransaction>($"select {C} from habitflow.payment_transactions order by created_at desc limit @limit", new { limit }, ct)).ToList(); public async Task<IReadOnlyList<PaymentTransaction>> ListByUserAsync(Guid userId, CancellationToken ct = default) => (await db.QueryAsync<PaymentTransaction>($"select {C} from habitflow.payment_transactions where user_id=@userId order by created_at desc", new { userId }, ct)).ToList(); }

public sealed class PaymentWebhookRepository(SqlExecutor db) : IPaymentWebhookRepository
{ private const string C = "id,provider,event_id,event_type,status,received_at,processed_at,user_id,subscription_id,payment_transaction_id,sanitized_payload::text as sanitized_payload,processing_error"; public Task CreateAsync(PaymentWebhookEvent e, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.payment_webhook_events(id,provider,event_id,event_type,status,received_at,processed_at,user_id,subscription_id,payment_transaction_id,sanitized_payload,processing_error) values(@Id,@Provider::text,@EventId,@EventType,@Status,@ReceivedAt,@ProcessedAt,@UserId,@SubscriptionId,@PaymentTransactionId,@SanitizedPayload::jsonb,@ProcessingError)", e, ct); public Task MarkProcessedAsync(Guid id, Guid? userId, Guid? subscriptionId, Guid? transactionId, string? error, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.payment_webhook_events set status=@status, processed_at=now(), user_id=@userId, subscription_id=@subscriptionId, payment_transaction_id=@transactionId, processing_error=@error where id=@id", new { id, userId, subscriptionId, transactionId, error, status = error is null ? "Processed" : "Failed" }, ct); public async Task<IReadOnlyList<PaymentWebhookEvent>> ListLatestAsync(int limit, CancellationToken ct = default) => (await db.QueryAsync<PaymentWebhookEvent>($"select {C} from habitflow.payment_webhook_events order by received_at desc limit @limit", new { limit }, ct)).ToList(); }

public sealed class PaymentAuditRepository(SqlExecutor db) : IPaymentAuditRepository
{ public Task CreateAsync(PaymentAuditLog a, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.payment_audit_logs(id,user_id,subscription_id,action,message,severity,metadata,created_at) values(@Id,@UserId,@SubscriptionId,@Action,@Message,@Severity,@Metadata::jsonb,@CreatedAt)", a, ct); }

public sealed class FinancialDashboardRepository(SqlExecutor db) : IFinancialDashboardRepository
{ public async Task<FinancialDashboard> GetDashboardAsync(CancellationToken ct = default) { var latestTx = (await db.QueryAsync<PaymentTransaction>("select id,user_id,subscription_id,provider,provider_payment_id,provider_preference_id,event_type,status,amount,currency,raw_status,sanitized_metadata::text as sanitized_metadata,created_at,updated_at from habitflow.payment_transactions order by created_at desc limit 20", null, ct)).ToList(); var webhooks = (await db.QueryAsync<PaymentWebhookEvent>("select id,provider,event_id,event_type,status,received_at,processed_at,user_id,subscription_id,payment_transaction_id,sanitized_payload::text as sanitized_payload,processing_error from habitflow.payment_webhook_events order by received_at desc limit 20", null, ct)).ToList(); var rows = await db.QuerySingleOrDefaultAsync<dynamic>("select coalesce(sum(amount) filter(where status='Approved'),0) approved, coalesce(sum(amount) filter(where status='Pending'),0) pending, coalesce(sum(amount) filter(where status in ('Rejected','Failed')),0) rejected from habitflow.payment_transactions", null, ct); var active = await db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.subscriptions where status='Active'", null, ct); var pending = await db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.subscriptions where status='Pending'", null, ct); var canceled = await db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.subscriptions where status='Canceled'", null, ct); var mrr = await db.QuerySingleOrDefaultAsync<decimal>("select coalesce(sum(case when plan_code='premium_monthly' then 14.90 when plan_code='premium_yearly' then 99.00/12 else 0 end),0) from habitflow.subscriptions where status='Active'", null, ct); return new((decimal)rows.approved, (decimal)rows.pending, (decimal)rows.rejected, active, pending, canceled, mrr, mrr * 12, latestTx, webhooks); } }
