using HabitFlow.Domain;

namespace HabitFlow.Infrastructure;

public sealed class ClientOnboardingRepository(SqlExecutor db) : IClientOnboardingRepository
{
    private const string Columns = "id,client_id,company_data_completed,billing_data_completed,first_user_invited,first_habit_created,plan_reviewed,completed,completed_at,created_at,updated_at";
    public async Task<ClientOnboarding> GetOrCreateAsync(Guid clientId, CancellationToken ct = default)
    {
        var existing = await db.QuerySingleOrDefaultAsync<ClientOnboarding>("select " + Columns + " from habitflow.client_onboarding where client_id=@clientId", new { clientId }, ct);
        if (existing is not null) return existing;
        var onboarding = new ClientOnboarding(Guid.NewGuid(), clientId, false, false, false, false, false, false, null, DateTime.UtcNow, DateTime.UtcNow);
        await db.ExecuteAsync("insert into habitflow.client_onboarding(id,client_id,company_data_completed,billing_data_completed,first_user_invited,first_habit_created,plan_reviewed,completed,completed_at,created_at,updated_at) values(@Id,@ClientId,@CompanyDataCompleted,@BillingDataCompleted,@FirstUserInvited,@FirstHabitCreated,@PlanReviewed,@Completed,@CompletedAt,@CreatedAt,@UpdatedAt)", onboarding, ct);
        return onboarding;
    }
    public Task UpdateStepAsync(Guid clientId, string step, bool completed, CancellationToken ct = default)
    {
        var allowed = new HashSet<string> { "company_data_completed", "billing_data_completed", "first_user_invited", "first_habit_created", "plan_reviewed", "completed" };
        if (!allowed.Contains(step)) throw new ArgumentOutOfRangeException(nameof(step));
        var completedAt = step == "completed" && completed ? ", completed_at=now()" : string.Empty;
        return db.ExecuteAsync($"update habitflow.client_onboarding set {step}=@completed, updated_at=now(){completedAt} where client_id=@clientId", new { clientId, completed }, ct);
    }
}

public sealed class ClientCommunicationRepository(SqlExecutor db) : IClientCommunicationRepository
{
    private const string Columns = "id,client_id,user_id,invoice_id,type,channel,title,message,status,sent_at,read_at,created_at";
    public Task CreateAsync(ClientCommunication c, CancellationToken ct = default) => db.ExecuteAsync("insert into habitflow.client_communications(id,client_id,user_id,invoice_id,type,channel,title,message,status,sent_at,read_at,created_at) values(@Id,@ClientId,@UserId,@InvoiceId,@Type,@Channel,@Title,@Message,@Status,@SentAt,@ReadAt,@CreatedAt)", c, ct);
    public Task<bool> ExistsAsync(Guid clientId, Guid? invoiceId, string type, string channel, CancellationToken ct = default) => db.QuerySingleOrDefaultAsync<bool>("select exists(select 1 from habitflow.client_communications where client_id=@clientId and invoice_id is not distinct from @invoiceId and type=@type and channel=@channel and status <> 'Canceled')", new { clientId, invoiceId, type, channel }, ct)!;
    public async Task<IReadOnlyList<ClientCommunication>> ListByClientAsync(Guid clientId, ClientCommunicationFilter filter, CancellationToken ct = default) => (await db.QueryAsync<ClientCommunication>("select " + Columns + " from habitflow.client_communications where client_id=@clientId and (@type is null or type=@type) and (@status is null or status=@status) order by created_at desc", new { clientId, type = filter.Type, status = filter.Status }, ct)).ToList();
    public async Task<IReadOnlyList<ClientCommunication>> ListAllAsync(ClientCommunicationFilter filter, CancellationToken ct = default) => (await db.QueryAsync<ClientCommunication>("select " + Columns + " from habitflow.client_communications where (@clientId is null or client_id=@clientId) and (@type is null or type=@type) and (@status is null or status=@status) order by created_at desc limit 500", new { clientId = filter.ClientId, type = filter.Type, status = filter.Status }, ct)).ToList();
    public Task MarkAsReadAsync(Guid clientId, Guid communicationId, DateTime readAt, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.client_communications set status='Read', read_at=@readAt where id=@communicationId and client_id=@clientId", new { clientId, communicationId, readAt }, ct);
}

public sealed class BillingCommunicationRuleRepository(SqlExecutor db) : IBillingCommunicationRuleRepository
{
    public async Task<IReadOnlyList<BillingCommunicationRule>> ListActiveAsync(CancellationToken ct = default) => (await db.QueryAsync<BillingCommunicationRule>("select id,code,name,trigger_type,days_offset,channel,title,message_template,is_active,created_at,updated_at from habitflow.billing_communication_rules where is_active=true order by trigger_type,days_offset", null, ct)).ToList();
}

public sealed class JobExecutionLogRepository(SqlExecutor db) : IJobExecutionLogRepository
{
    public async Task<Guid> StartAsync(string jobName, CancellationToken ct = default) { var id = Guid.NewGuid(); await db.ExecuteAsync("insert into habitflow.job_execution_logs(id,job_name,status,started_at,created_at) values(@id,@jobName,'Running',now(),now())", new { id, jobName }, ct); return id; }
    public Task FinishAsync(Guid id, string status, int processedCount, string? errorMessage, CancellationToken ct = default) => db.ExecuteAsync("update habitflow.job_execution_logs set status=@status, finished_at=now(), duration_ms=(extract(epoch from (now()-started_at))*1000)::bigint, processed_count=@processedCount, error_message=@errorMessage where id=@id", new { id, status, processedCount, errorMessage }, ct);
}

public sealed class SuperAdminOperationalRepository(SqlExecutor db) : ISuperAdminOperationalRepository
{
    public async Task<IReadOnlyList<SuperAdminPlanRow>> ListPlansAsync(CancellationToken ct = default) => (await db.QueryAsync<SuperAdminPlanRow>(@"select p.code, p.name, p.price_monthly, p.price_yearly, p.habit_limit, p.reports_enabled, p.advanced_reports_enabled, p.is_active, p.is_public, count(c.id)::int clients_using, coalesce(sum(case when c.subscription_status in ('Active','Trial') then coalesce(p.price_monthly,0) else 0 end),0) estimated_revenue from habitflow.plans p left join habitflow.clients c on lower(c.plan::text)=replace(lower(p.code),'_monthly','') group by p.code,p.name,p.price_monthly,p.price_yearly,p.habit_limit,p.reports_enabled,p.advanced_reports_enabled,p.is_active,p.is_public order by p.price_monthly nulls first", null, ct)).ToList();
    public async Task<IReadOnlyList<SuperAdminSubscriptionRow>> ListSubscriptionsAsync(CancellationToken ct = default) => (await db.QueryAsync<SuperAdminSubscriptionRow>(@"select s.id, coalesce(s.client_id, c.id) client_id, coalesce(c.name,'Cliente não vinculado') client_name, s.plan_code, s.status, s.billing_cycle, s.current_period_start, s.current_period_end, s.trial_ends_at, s.canceled_at, c.next_due_date from habitflow.client_subscriptions s left join habitflow.clients c on c.id=s.client_id order by s.updated_at desc limit 500", null, ct)).ToList();
    public async Task<IReadOnlyList<SuperAdminPaymentRow>> ListPaymentsAsync(string? status = null, CancellationToken ct = default) => (await db.QueryAsync<SuperAdminPaymentRow>(@"select i.id, i.client_id, c.name client_name, i.invoice_number, i.amount, i.due_date, coalesce(i.payment_method,'Manual') method, i.status, i.paid_at, i.checkout_url, i.provider_payment_id from habitflow.client_invoices i join habitflow.clients c on c.id=i.client_id where (@status is null or i.status=@status) order by i.due_date desc limit 500", new { status }, ct)).ToList();
    public async Task<IReadOnlyList<SuperAdminAuditRow>> ListAuditAsync(CancellationToken ct = default) => (await db.QueryAsync<SuperAdminAuditRow>(@"select created_at, coalesce(actor_email,'sistema') actor_email, action, target_type, target_id, reason, metadata::text metadata from habitflow.superadmin_audit_logs order by created_at desc limit 500", null, ct)).ToList();
    public async Task ChangeClientPlanAsync(Guid clientId, string planCode, string reason, string actorEmail, CancellationToken ct = default){await db.ExecuteAsync(@"update habitflow.clients set plan=@planCode, subscription_status=case when @planCode='Free' then 'Free' else 'Active' end, benefits_status=case when @planCode='Enterprise' then 'EnterpriseActive' when @planCode='Premium' then 'PremiumActive' else 'Free' end, updated_at=now() where id=@clientId; insert into habitflow.superadmin_audit_logs(id,actor_email,action,target_type,target_id,reason,metadata,created_at) values(gen_random_uuid(),@actorEmail,'client.change_plan','Client',@clientId,@reason,jsonb_build_object('plan',@planCode),now())",new{clientId,planCode,reason,actorEmail},ct);}
    public Task MarkInvoicePaidAsync(Guid invoiceId, string reason, string actorEmail, CancellationToken ct = default)=>db.ExecuteAsync(@"with inv as (update habitflow.client_invoices set status='Approved', paid_at=now(), updated_at=now() where id=@invoiceId returning client_id,id) update habitflow.clients c set payment_status='Approved', last_payment_at=now(), overdue_since=null, grace_period_until=null, benefits_status=case when c.plan='Enterprise' then 'EnterpriseActive' when c.plan='Premium' then 'PremiumActive' else 'Free' end, updated_at=now() from inv where c.id=inv.client_id; insert into habitflow.client_entitlement_events(id,client_id,event_type,reason,created_at) select gen_random_uuid(), client_id, 'PaymentApproved', @reason, now() from habitflow.client_invoices where id=@invoiceId; insert into habitflow.superadmin_audit_logs(id,actor_email,action,target_type,target_id,reason,metadata,created_at) values(gen_random_uuid(),@actorEmail,'invoice.mark_paid','Invoice',@invoiceId,@reason,'{}'::jsonb,now())",new{invoiceId,reason,actorEmail},ct);
    public Task MarkInvoiceOverdueAsync(Guid invoiceId, string reason, string actorEmail, CancellationToken ct = default)=>db.ExecuteAsync(@"with inv as (update habitflow.client_invoices set status='Overdue', updated_at=now() where id=@invoiceId returning client_id,due_date) update habitflow.clients c set payment_status='Overdue', overdue_since=coalesce(inv.due_date,current_date), benefits_status=case when coalesce(inv.due_date,current_date) <= current_date - 5 then case when c.plan='Enterprise' then 'EnterpriseBlocked' when c.plan='Premium' then 'PremiumBlocked' else 'Free' end else c.benefits_status end, updated_at=now() from inv where c.id=inv.client_id; insert into habitflow.superadmin_audit_logs(id,actor_email,action,target_type,target_id,reason,metadata,created_at) values(gen_random_uuid(),@actorEmail,'invoice.mark_overdue','Invoice',@invoiceId,@reason,'{}'::jsonb,now())",new{invoiceId,reason,actorEmail},ct);
    public Task CancelSubscriptionAsync(Guid subscriptionId, string reason, string actorEmail, CancellationToken ct = default)=>db.ExecuteAsync(@"with sub as (update habitflow.client_subscriptions set status='Canceled', canceled_at=now(), updated_at=now() where id=@subscriptionId returning client_id) update habitflow.clients c set subscription_status='Canceled', benefits_status='Free', updated_at=now() from sub where c.id=sub.client_id; insert into habitflow.superadmin_audit_logs(id,actor_email,action,target_type,target_id,reason,metadata,created_at) values(gen_random_uuid(),@actorEmail,'subscription.cancel','Subscription',@subscriptionId,@reason,'{}'::jsonb,now())",new{subscriptionId,reason,actorEmail},ct);
    public Task ReactivateSubscriptionAsync(Guid subscriptionId, string reason, string actorEmail, CancellationToken ct = default)=>db.ExecuteAsync(@"with sub as (update habitflow.client_subscriptions set status='Active', canceled_at=null, updated_at=now() where id=@subscriptionId returning client_id,plan_code) update habitflow.clients c set subscription_status='Active', benefits_status=case when sub.plan_code ilike 'enterprise%' then 'EnterpriseActive' when sub.plan_code ilike 'premium%' then 'PremiumActive' else 'Free' end, updated_at=now() from sub where c.id=sub.client_id; insert into habitflow.superadmin_audit_logs(id,actor_email,action,target_type,target_id,reason,metadata,created_at) values(gen_random_uuid(),@actorEmail,'subscription.reactivate','Subscription',@subscriptionId,@reason,'{}'::jsonb,now())",new{subscriptionId,reason,actorEmail},ct);
    public async Task<IReadOnlyList<SchemaMigrationStatus>> ListAppliedMigrationsAsync(CancellationToken ct = default)=> (await db.QueryAsync<SchemaMigrationStatus>("select id,name,true applied,applied_at from habitflow.schema_migrations order by id",null,ct)).ToList();
    public async Task<SystemHealthStatus> BuildSystemHealthAsync(IReadOnlyList<SchemaMigrationStatus> expected, CancellationToken ct = default){var applied=await ListAppliedMigrationsAsync(ct); var tables=(await db.QueryAsync<string>("select unnest(array['clients','users','plans','client_invoices','client_subscriptions','client_communications','client_onboarding','job_execution_logs','schema_migrations']) except select table_name from information_schema.tables where table_schema='habitflow'",null,ct)).ToList(); var plans=await db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.plans",null,ct); var templates=await db.QuerySingleOrDefaultAsync<int>("select count(*) from habitflow.habit_templates",null,ct); return new SystemHealthStatus(true, expected.Select(e=> applied.FirstOrDefault(a=>a.Id==e.Id) ?? e).ToList(), tables, Array.Empty<string>(), Array.Empty<string>(), plans, templates, false, Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production", typeof(SuperAdminOperationalRepository).Assembly.GetName().Version?.ToString() ?? "dev", Environment.GetEnvironmentVariable("ASPNETCORE_URLS") ?? "http://localhost:5097", false);}
}
