set search_path to habitflow, public;
create table if not exists habitflow.roles(id uuid primary key,code varchar(80) unique not null,name varchar(120) not null,scope varchar(30) not null check(scope in ('Platform','Client')),description text,is_system boolean not null default false,is_active boolean not null default true);
create table if not exists habitflow.permissions(code varchar(120) primary key,name varchar(160) not null,description text,category varchar(80) not null);
create table if not exists habitflow.role_permissions(role_id uuid not null references habitflow.roles(id),permission_code varchar(120) not null references habitflow.permissions(code),primary key(role_id,permission_code));
create table if not exists habitflow.user_role_assignments(id uuid primary key,user_id uuid not null references habitflow.users(id),role_id uuid not null references habitflow.roles(id),client_id uuid null references habitflow.clients(id),assigned_by_user_id uuid null references habitflow.users(id),created_at timestamp not null default now(),revoked_at timestamp null);
create index if not exists ix_user_role_assignments_active on habitflow.user_role_assignments(user_id,client_id) where revoked_at is null;
insert into habitflow.roles(id,code,name,scope,is_system) values
('30000000-0000-0000-0000-000000000001','super_admin','Super Administrador','Platform',true),('30000000-0000-0000-0000-000000000002','finance_manager','Gestor Financeiro','Platform',true),('30000000-0000-0000-0000-000000000003','support_manager','Atendimento','Platform',true),('30000000-0000-0000-0000-000000000004','customer_success','Relacionamento','Platform',true),('30000000-0000-0000-0000-000000000005','auditor_readonly','Auditor','Platform',true),('30000000-0000-0000-0000-000000000006','account_owner','Proprietário da conta','Client',true),('30000000-0000-0000-0000-000000000007','account_admin','Administrador da conta','Client',true),('30000000-0000-0000-0000-000000000008','member','Membro','Client',true) on conflict(code) do update set name=excluded.name;
insert into habitflow.permissions(code,name,category) select code,replace(code,'.',' '),split_part(code,'.',1) from unnest(array['Platform.FullAccess','Platform.Clients.View','Platform.Clients.Manage','Platform.Users.View','Platform.Users.Manage','Platform.Plans.View','Platform.Plans.Manage','Platform.Billing.View','Platform.Billing.Manage','Platform.Support.Manage','Platform.Audit.View','Platform.Settings.Manage','Client.Account.Manage','Client.Users.Manage','Client.Billing.View','Client.Billing.Manage','Client.Routines.Use','Client.Reports.View','Client.SharedFeatures.Use']) code on conflict do nothing;
insert into habitflow.role_permissions select r.id,p.code from habitflow.roles r cross join habitflow.permissions p where r.code='super_admin' or (r.code='finance_manager' and p.code like 'Platform.Billing.%') or (r.code='support_manager' and p.code in ('Platform.Clients.View','Platform.Users.View','Platform.Support.Manage')) or (r.code='auditor_readonly' and p.code in ('Platform.Audit.View','Platform.Clients.View','Platform.Users.View')) or (r.code='account_owner' and p.code like 'Client.%') on conflict do nothing;

