namespace HabitFlow.Domain;

public interface IPlanRepository { Task<IReadOnlyList<Plan>> GetPublicPlansAsync(CancellationToken ct = default); Task<Plan?> GetByCodeAsync(string code, CancellationToken ct = default); }
public interface ISubscriptionRepository { Task<Subscription?> GetActiveOrLatestByUserIdAsync(Guid userId, CancellationToken ct = default); Task<Subscription?> GetByIdAsync(Guid id, CancellationToken ct = default); Task<Subscription?> GetByProviderPaymentIdAsync(string providerPaymentId, CancellationToken ct = default); Task CreateAsync(Subscription subscription, CancellationToken ct = default); Task UpdateAsync(Subscription subscription, CancellationToken ct = default); Task UpdateCheckoutAsync(Guid id, string? checkoutUrl, string? providerSubscriptionId, CancellationToken ct = default); Task<IReadOnlyList<Subscription>> ListByStatusAsync(SubscriptionStatus? status, CancellationToken ct = default); }
public interface IPaymentTransactionRepository { Task CreateAsync(PaymentTransaction transaction, CancellationToken ct = default); Task<IReadOnlyList<PaymentTransaction>> ListLatestAsync(int limit, CancellationToken ct = default); Task<IReadOnlyList<PaymentTransaction>> ListByUserAsync(Guid userId, CancellationToken ct = default); }
public interface IPaymentWebhookRepository { Task CreateAsync(PaymentWebhookEvent webhookEvent, CancellationToken ct = default); Task MarkProcessedAsync(Guid id, Guid? userId, Guid? subscriptionId, Guid? transactionId, string? error, CancellationToken ct = default); Task<IReadOnlyList<PaymentWebhookEvent>> ListLatestAsync(int limit, CancellationToken ct = default); }
public interface IPaymentAuditRepository { Task CreateAsync(PaymentAuditLog auditLog, CancellationToken ct = default); }
public interface IPaymentProviderService { Task<HabitFlow.Shared.Result<CheckoutPreference>> CreateCheckoutPreferenceAsync(CheckoutRequest request, Subscription subscription, Plan plan, CancellationToken ct = default); Task<HabitFlow.Shared.Result<ProviderPayment>> GetPaymentAsync(string providerPaymentId, CancellationToken ct = default); Task<HabitFlow.Shared.Result> ValidateWebhookAsync(string payload, IReadOnlyDictionary<string,string> headers, CancellationToken ct = default); }
public interface IFinancialDashboardRepository { Task<FinancialDashboard> GetDashboardAsync(CancellationToken ct = default); }
