namespace HabitFlow.Domain;
public interface IUserRepository{Task<User?> GetByIdAsync(Guid id,CancellationToken ct=default);Task<User?> GetByEmailAsync(string email,CancellationToken ct=default);Task<IReadOnlyList<User>> SearchAsync(string? term,CancellationToken ct=default);Task CreateAsync(User user,CancellationToken ct=default);Task UpdateAsync(User user,CancellationToken ct=default);Task AddLoginAttemptAsync(LoginAttempt attempt,CancellationToken ct=default);} 
public interface IHabitRepository{Task<int> CountActiveByUserAsync(Guid userId,CancellationToken ct=default);Task<IReadOnlyList<Habit>> ListByUserAsync(Guid userId,CancellationToken ct=default);Task<Habit?> GetAsync(Guid id,CancellationToken ct=default);Task CreateAsync(Habit habit,CancellationToken ct=default);Task UpdateAsync(Habit habit,CancellationToken ct=default);} 
public interface IHabitCompletionRepository{Task<IReadOnlyList<HabitCompletion>> ListByUserAsync(Guid userId,DateOnly? from=null,CancellationToken ct=default);Task AddAsync(HabitCompletion completion,CancellationToken ct=default);Task DeleteAsync(Guid habitId,DateOnly date,CancellationToken ct=default);} 
public interface IAuditRepository{Task AddSystemAsync(SystemAuditLog log,CancellationToken ct=default);Task<IReadOnlyList<SystemAuditLog>> RecentAsync(CancellationToken ct=default);} public interface IAdminAuditRepository{Task AddAsync(AdminAuditLog log,CancellationToken ct=default);} 
public interface ISettingsRepository{Task<SystemSetting?> GetAsync(string key,CancellationToken ct=default);Task UpsertAsync(SystemSetting setting,CancellationToken ct=default);Task<IReadOnlyList<SystemSetting>> ListAsync(CancellationToken ct=default);} 
public interface ISupportRepository{Task CreateTicketAsync(SupportTicket ticket,CancellationToken ct=default);Task AddMessageAsync(SupportMessage message,CancellationToken ct=default);Task<IReadOnlyList<SupportTicket>> ListByUserAsync(Guid userId,CancellationToken ct=default);} 
public interface ILgpdRepository{Task CreateAsync(LgpdRequest request,CancellationToken ct=default);Task<IReadOnlyList<LgpdRequest>> ListByUserAsync(Guid userId,CancellationToken ct=default);} 
public interface IBillingRepository{Task AddAsync(BillingEvent billingEvent,CancellationToken ct=default);} 
