import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const out=path.join(root,'artifacts/v6120/screenshots');const report=path.join(root,'artifacts/v6120/visual-report.md');
const sizes=[[1600,900],[1440,900],[1366,768],[1280,720],[1180,820],[1024,768],[912,1368],[820,1180],[768,1024],[430,932],[414,896],[390,844],[375,812],[360,800],[320,568],[280,653],[240,320],[192,256]];
const routes={public:['/','/plans','/privacy','/help'],authenticated:['/dashboard','/my-day','/habits','/goals','/progress/calendar','/reports','/habit-library','/account/privacy','/account/plan/usage','/notifications','/reminders']};const rows=[];
test.beforeAll(async()=>fs.mkdir(out,{recursive:true}));test.afterAll(async()=>fs.writeFile(report,['# HabitFlow v6.12.0 — evidência visual real','',`Gerado (UTC): ${new Date().toISOString()}`,'','| Rota | Viewport | Contexto | Screenshot | HTTP | Console errors | Overflow horizontal | Header overlap | Bottom nav overlap | Resultado |','|---|---|---|---|---:|---:|---|---|---|---|',...rows,''].join('\n')));
for(const [context,list] of Object.entries(routes))for(const route of list)for(const [width,height] of sizes)test(`${context} ${route} ${width}x${height}`,async({page})=>{
  test.skip(context==='authenticated'&&!process.env.HABITFLOW_AUTH_STORAGE,'auth storage required');const errors=[];page.on('console',m=>m.type()==='error'&&errors.push(m.text()));page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height});const response=await page.goto(route,{waitUntil:'networkidle'});const status=response?.status()??0;
  const metrics=await page.evaluate(()=>{const h=document.querySelector('[data-header-root]')?.getBoundingClientRect();const m=document.querySelector('main')?.getBoundingClientRect();const b=document.querySelector('.mobile-bottom-nav-v4')?.getBoundingClientRect();return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,headerOverlap:Boolean(h&&m&&m.top<h.bottom-1),bottomOverlap:Boolean(b?.height&&m&&m.bottom>b.top&&parseFloat(getComputedStyle(document.body).paddingBottom||'0')<b.height)}});
  const slug=route==='/'?'home':route.slice(1).replaceAll('/','-');const file=`${context}-${slug}-${width}x${height}.png`;await page.screenshot({path:path.join(out,file),fullPage:true});const pass=status<400&&!errors.length&&!Object.values(metrics).some(Boolean);rows.push(`| ${route} | ${width}x${height} | ${context} | [${file}](screenshots/${file}) | ${status} | ${errors.length} | ${metrics.overflow?'sim':'não'} | ${metrics.headerOverlap?'sim':'não'} | ${metrics.bottomOverlap?'sim':'não'} | ${pass?'PASS':'FAIL'} |`);
  expect(status).toBeLessThan(400);expect(errors).toEqual([]);expect(metrics).toEqual({overflow:false,headerOverlap:false,bottomOverlap:false});
});
